### ISSUE TITLE
FAQ Section- Dropdown Cards

### ISSUE THREAD

**Issue by octoberstrike** [HiraethOctoberStrike/octoberstrike.com#41]
**Feature Description**
We will need to build out our FAQ page, starting with a card component which expands and collapses with an arrow.

**Checklist**
- [ ] Card design
- [ ] Card opens and closes on click

**[Figma Link](https://www.figma.com/file/zBXRu0Gb5WquL5FXddFG1u/strike?node-id=370%3A3)**
> You may need to switch to current page in the top left

**Screenshot**
![v2_Faq](https://user-images.githubusercontent.com/88251443/128530216-e12cdeea-1b07-416e-9997-83d3ce29d02d.jpg)

**Comment by comrade-kirby** [comment]
subdivided into separate tasks
